wvd-templates/diagnostics-sample/src/MSFT.WVD.Diagnostics/Controllers/DiagonizeIssuesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Xml;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MSFT.WVD.Diagnostics.Common.Models;
using MSFT.WVD.Diagnostics.Common.Services;
using MSFT.WVD.Diagnostics.Models;
using Newtonsoft.Json;

namespace MSFT.WVD.Diagnostics.Controllers
{
    public class DiagnoseIssuesController : Controller
    {
        private readonly ILogger _logger;
        private readonly DiagnozeService _diagnozeService;
        private readonly UserSessionService _userSessionService;
        private readonly LogAnalyticsService _logAnalyticsService;
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly CommonService _commonService;
        public string tenantGroupName, tenant, accessToken;
        public DiagnoseIssuesController(IHostingEnvironment hostingEnvironment, ILogger<DiagnoseIssuesController> logger, DiagnozeService diagnozeService, UserSessionService userSessionService, LogAnalyticsService logAnalyticsService, CommonService commonService)
        {
            _commonService = commonService;
            _hostingEnvironment = hostingEnvironment;
            _logger = logger;
            _diagnozeService = diagnozeService;
            _userSessionService = userSessionService;
            _logAnalyticsService = logAnalyticsService;
        }
        public IActionResult Index()
        {
            //var role = HttpContext.Session.Get<IEnumerable<RoleAssignment>>("WVDRoles").FirstOrDefault();
            var role = HttpContext.Session.Get<RoleAssignment>("SelectedRole");
            var viewData = new DiagonizePageViewModel() { SelectedRole = role, DiagonizeQuery = new DiagonizeQuery() { StartDate = DateTime.Now.AddDays(-2), EndDate = DateTime.Now } };
            return View(viewData);
        }
        public IActionResult returnToIndex()
        {

            var role = HttpContext.Session.Get<RoleAssignment>("SelectedRole");
            var viewData = new DiagonizePageViewModel() { SelectedRole = role, DiagonizeQuery = new DiagonizeQuery() { StartDate = DateTime.Now.AddDays(-2), EndDate = DateTime.Now } };
            return View(viewData);
        }
        [HttpPost]
        public async Task<IActionResult> Index(DiagonizePageViewModel data)
        {
            var viewData = new DiagonizePageViewModel();
            if (ModelState.IsValid)
            {

                tenantGroupName = HttpContext.Session.Get<string>("SelectedTenantGroupName");
                tenant = HttpContext.Session.Get<string>("SelectedTenantName");
                if (string.IsNullOrEmpty(tenantGroupName) || string.IsNullOrEmpty(tenant))
                {
                    return RedirectToAction("Error", "Home", new ErrorDetails() { StatusCode = (int)HttpStatusCode.Forbidden, Message = "Invalid tenant group name or tenant name." });
                }
                else
                {

                    var refreshtoken = await HttpContext.GetTokenAsync("refresh_token").ConfigureAwait(false);
                    accessToken = _commonService.GetAccessTokenWVD(refreshtoken); //await HttpContext.GetTokenAsync("access_token");
                    string startDate, endDate = "";
                    if (data.DiagonizeQuery.StartDate == null)
                    {
                        startDate = $"{DateTime.Now.ToUniversalTime().AddDays(-7).ToString("yyyy-MM-dd")}T00:00:00Z";
                        endDate = $"{DateTime.Now.ToUniversalTime().ToString("yyyy-MM-dd")}T00:00:00Z";
                    }
                    else
                    {
                        startDate = data.DiagonizeQuery.StartDate.ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ");//+"T00:00:00Z";
                        endDate = data.DiagonizeQuery.EndDate.ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ");//+"T00: 00:00Z";
                    }



                    string activityoutcome = data.DiagonizeQuery.ActivityOutcome.ToString();
                    if (data.DiagonizeQuery.ActivityType == ActivityType.Management)
                    {
                        _logger.LogInformation($"Service call to get management activity details for selected tenant group {tenantGroupName} and tenant {tenant}");
                        //call from service layer
                        viewData.ManagementActivity = await _diagnozeService.GetManagementActivities(accessToken, data.DiagonizeQuery.UPN, tenantGroupName, tenant, startDate, endDate, activityoutcome).ConfigureAwait(false);
                        if (viewData.ManagementActivity?.Count > 0 && viewData.ManagementActivity[0].ErrorDetails != null)
                        {
                            _logger.LogError($"Error Occured : {viewData.ManagementActivity[0].ErrorDetails.Message}");
                            return RedirectToAction("Error", "Home", new ErrorDetails() { StatusCode = (int)viewData.ManagementActivity[0].ErrorDetails.StatusCode, Message = "Access Denied! You are not authorized to get list of activities.Please contact system administrator" });
                        }
                        viewData.ActivityType = viewData.ManagementActivity?.Count() > 0 ? ActivityType.Management : ActivityType.None;
                    }
                    else if (data.DiagonizeQuery.ActivityType == ActivityType.Connection)
                    {
                        _logger.LogInformation($"Service Call  to get connection activity details for selected tenant group {tenantGroupName} and tenant {tenant}");

                        //call from service layer
                        viewData.ConnectionActivity = await _diagnozeService.GetConnectionActivities(accessToken, data.DiagonizeQuery.UPN, tenantGroupName, tenant, startDate, endDate, activityoutcome).ConfigureAwait(false);
                        if (viewData.ConnectionActivity?.Count > 0 && viewData.ConnectionActivity[0].ErrorDetails != null)
                        {
                            _logger.LogError($"Error Occured : {viewData.ConnectionActivity[0].ErrorDetails.Message}");
                            return RedirectToAction("Error", "Home", new ErrorDetails() { StatusCode = (int)viewData.ConnectionActivity[0].ErrorDetails.StatusCode, Message = "Access Denied! You are not authorized to get list of activities.Please contact system administrator" });
                        }

                        viewData.ActivityType = viewData.ConnectionActivity?.Count() > 0 ? ActivityType.Connection : ActivityType.None;
                    }
                    else if (data.DiagonizeQuery.ActivityType == ActivityType.Feed)
                    {
                        _logger.LogInformation($"Service call to get feed activity details for selected tenant group {tenantGroupName} and tenant {tenant}");

                        viewData.FeedActivity = await _diagnozeService.GetFeedActivities(accessToken, data.DiagonizeQuery.UPN, tenantGroupName, tenant, startDate, endDate, activityoutcome).ConfigureAwait(false);
                        if (viewData.FeedActivity?.Count > 0 && viewData.FeedActivity[0].ErrorDetails != null)
                        {
                            _logger.LogError($"Error Occured : {viewData.FeedActivity[0].ErrorDetails.Message}");
                            return RedirectToAction("Error", "Home", new ErrorDetails() { StatusCode = (int)viewData.FeedActivity[0].ErrorDetails.StatusCode, Message = "Access Denied!You are not authorized to get list of activities.Please contact system administrator" });
                        }
                        viewData.ActivityType = viewData.FeedActivity?.Count() > 0 ? ActivityType.Feed : ActivityType.None;
                    }
                }


            }
            HttpContext.Session.Set<DiagonizeQuery>("SearchQuery", data.DiagonizeQuery);
            HttpContext.Session.Set<List<ConnectionActivity>>("ConnectionActivity", viewData.ConnectionActivity);
            viewData.DiagonizeQuery = data.DiagonizeQuery;
            return View("SearchResults", viewData);
        }

        public async Task<IActionResult> SearchResults()
        {
            var searchQuery = HttpContext.Session.Get<DiagonizeQuery>("SearchQuery");
            RoleAssignment role = HttpContext.Session.Get<RoleAssignment>("SelectedRole");
            if (searchQuery != null)
            {
                return await Index(new DiagonizePageViewModel() { SelectedRole = role, DiagonizeQuery = searchQuery });
            }
            else
            { return RedirectToAction("Index"); }
        }
        public IActionResult GetUserSessions(DiagnoseDetailPageViewModel data)
        {
            return View("UserSessions", data);
        }

        public async Task<List<UserSession>> GetUserSessions(string accessToken, string tenantGroupName, string tenant, string hostPoolName, string hostName)
        {
            var data = await _userSessionService.GetUserSessions(accessToken, tenantGroupName, tenant, hostPoolName, hostName).ConfigureAwait(false);
            return data;
        }


        [HttpPost]
        public async Task<IActionResult> LogOffUserSession(DiagnoseDetailPageViewModel data)
        {
            var viewData = new LogOffUserQuery();
            tenantGroupName = HttpContext.Session.Get<string>("SelectedTenantGroupName");
            tenant = HttpContext.Session.Get<string>("SelectedTenantName");
            var refreshtoken = await HttpContext.GetTokenAsync("refresh_token").ConfigureAwait(false);
            accessToken = _commonService.GetAccessTokenWVD(refreshtoken); //await HttpContext.GetTokenAsync("access_token");

            var messageStatus = new List<MessageStatus>();

wvd-templates/diagnostics-sample/src/MSFT.WVD.Diagnostics/Views/DiagnoseIssues/Index.cshtml
@model DiagonizePageViewModel
@using MSFT.WVD.Diagnostics.Common.Models
@{
    ViewData["Title"] = "Diagnose Issues";
}
<div class="width-100 content-section">
    <h2>Search activity feed</h2>
    <br />
    <form asp-controller="DiagnoseIssues" asp-action="IssuesInterval" method="post" id="myform" asp-route-returnUrl="@Context.Request.Path" role="form">
        <div class="ms-Grid" dir="ltr">
            <div class="ms-Grid-row">
                <div class="form-wrap ms-Grid-col ms-xxxl3 ms-xxl3 ms-xl12 m-b-20">
                    <label asp-for="DiagonizeQuery.UPN" class="control-label ms-xxxl2 ms-xxl2 ms-xl2"><b>User UPN</b><span class="red">*</span></label>
                    <div class="input-wrap ms-xxxl10 ms-xxl12 ms-xl12">
                        <input asp-for="@Model.DiagonizeQuery.UPN" class="form-control" id="upn" placeholder="Enter User UPN" />
                        <span asp-validation-for="DiagonizeQuery.UPN" id="validateUpn" class="error-msg validate"></span>
                    </div>
                </div>
                <div class="form-wrap ms-Grid-col ms-xxxl3 ms-xxl3 ms-xl12 m-b-20">
                    <label asp-for="DiagonizeQuery.ActivityType" class="control-label ms-xxxl2 ms-xxl2 ms-xl2"><b>Activity type</b><span class="red">*</span></label>
                    <div class="input-wrap ms-xxxl10 ms-xxl12 ms-xl12">
                        <select size="1" asp-for="DiagonizeQuery.ActivityType" asp-items="Html.GetEnumSelectList<ActivityType>().Where(x=> x.Text != ActivityType.None.ToString() ).ToList()" class="form-control  width-100 " id="activityType"></select>
                    </div>
                </div>
                <div class="form-wrap ms-Grid-col ms-xxxl3 ms-xxl4 ms-xl12 p-l-r-15 m-b-20">
                    <button type="submit" class="ms-Button primary-btn" id="process">
                        <span class="ms-Button-label">Search</span>
                    </button>
                </div>
            </div>
        </div>
    </form>
    <hr />
    @if (Model.ConnectionActivity == null || Model.ManagementActivity == null || Model.FeedActivity == null || Model.ConnectionActivity.Count == 0 || Model.ManagementActivity.Count == 0 || Model.FeedActivity.Count == 0)
    {
        <div id="loader1" class="loader"></div>
    }
    <div class="ContextualMenuWrap">
        <div class="ms-ContextualMenuExample filter-btn float-right">
            <button class="ms-Button ms-Button--default">
                <span class="ms-Button-label"><i class="ms-Icon ms-Icon--Filter" aria-hidden="true"></i>Filter</span>
            </button>
            <ul class="ms-ContextualMenu is-hidden ms-ContextualMenu--multiselect">
                <li class="ms-ContextualMenu-item ms-ContextualMenu-item--header"><i class="ms-Icon ms-Icon--Filter" aria-hidden="true"></i> <a style="text-decoration:none; color:#0078d7; padding-left:8px;" asp-controller="DiagnoseIssues" asp-action="ClearFilter"><b>Clear all Filters</b></a> </li>
                <li class="ms-ContextualMenu-item ms-ContextualMenu-item--divider"></li>
                <li class="ms-ContextualMenu-item ms-ContextualMenu-item--header"><b>Issues from</b></li>
                <li class="ms-ContextualMenu-item">
                    @{
                        IDictionary<string, string> routeData = new Dictionary<string, string>();
                        routeData.Add("interval", "Lastonehour");
                        routeData.Add("upn", Model.DiagonizeQuery.UPN);
                       

                    }
                  
                    <a class="ms-ContextualMenu-link" tabindex="1" asp-controller="DiagnoseIssues" asp-action="IssuesInterval" asp-all-route-data="routeData">Last hour</a>
                </li>
                <li class="ms-ContextualMenu-item">
                    @{
                        IDictionary<string, string> routeData1 = new Dictionary<string, string>();
                        routeData1.Add("interval", "sixhoursago");
                        routeData1.Add("upn", Model.DiagonizeQuery.UPN);
                    }
                    <a class="ms-ContextualMenu-link" tabindex="1" asp-controller="DiagnoseIssues" asp-action="IssuesInterval" asp-all-route-data="routeData1">6 hours ago</a>
                </li>
                <li class="ms-ContextualMenu-item">
                    @{
                        IDictionary<string, string> routeData2 = new Dictionary<string, string>();
                        routeData2.Add("interval", "onedayago");
                        routeData2.Add("upn", Model.DiagonizeQuery.UPN);
                    }
                    <a class="ms-ContextualMenu-link" tabindex="1" asp-controller="DiagnoseIssues" asp-action="IssuesInterval" asp-all-route-data="routeData2">1 day ago</a>
                </li>
                <li class="ms-ContextualMenu-item">
                    @{
                        IDictionary<string, string> routeData3 = new Dictionary<string, string>();
                        routeData3.Add("interval", "oneweekago");
                        routeData3.Add("upn", Model.DiagonizeQuery.UPN);
                    }
                    <a class="ms-ContextualMenu-link" tabindex="1" asp-controller="DiagnoseIssues" asp-action="IssuesInterval" asp-all-route-data="routeData3">1 week ago</a>
                </li>
                <li class="ms-ContextualMenu-item ms-ContextualMenu-item--divider"></li>
                <li class="ms-ContextualMenu-item ms-ContextualMenu-item--header"><b>Outcome</b></li>
                <li class="ms-ContextualMenu-item">
                    @{
                        IDictionary<string, string> routeData4 = new Dictionary<string, string>();
                        routeData4.Add("outcome", "Failure");
                        routeData4.Add("upn", Model.DiagonizeQuery.UPN);
                    }
                    <a class="ms-ContextualMenu-link" tabindex="1" asp-controller="DiagnoseIssues" asp-action="IssuesInterval" asp-all-route-data="routeData4">Failed</a>
                </li>
                <li class="ms-ContextualMenu-item">
                    @{
                        IDictionary<string, string> routeData5 = new Dictionary<string, string>();
                        routeData5.Add("outcome", "Success");
                        routeData5.Add("upn", Model.DiagonizeQuery.UPN);
                    }
                    <a class="ms-ContextualMenu-link" tabindex="1" asp-controller="DiagnoseIssues" asp-action="IssuesInterval" asp-all-route-data="routeData5">Success</a>
                </li>
                <li class="ms-ContextualMenu-item">
                    @{
                        IDictionary<string, string> routeData6 = new Dictionary<string, string>();
                        routeData6.Add("outcome", "All");
                        routeData6.Add("upn", Model.DiagonizeQuery.UPN);
                    }
                    <a class="ms-ContextualMenu-link" tabindex="1" asp-controller="DiagnoseIssues" asp-action="IssuesInterval" asp-all-route-data="routeData6">All</a>
                </li>
            </ul>
        </div>
        <div class="clear"></div>
    </div>
    <table class="ms-Table">
        <thead>
            <tr>

                <th asp-for="Start Time">Start time</th>
                <th asp-for="End Time">End time</th>
                <th asp-for="Outcome">Outcome</th>
                <th asp-for="Type">Service error</th>
                <th asp-for="Error">Error code</th>
                <th asp-for="Session host">Session host</th>
                <th asp-for="Client">Client</th>
                <th asp-for="Client Ip">Client IP</th>
                <th asp-for="Host pool">Host pool</th>
                <th asp-for="Tenant">Tenant</th>
                <th asp-for="Activity Id">Activity ID</th>
            </tr>
        </thead>
    </table>
    <div id="Indexnodata">
        <h5 style="text-align:center">No data yet.</h5><p style="text-align:center">Please search User UPN to see data</p>
    </div>
</div>

<script>
    (function () {
        document.getElementById("Diagnosebreadcrumb").style.display = "block";
        var TableElements = document.querySelectorAll(".ms-Table");
        for (var i = 0; i < TableElements.length; i++) {
            new fabric['Table'](TableElements[i]);
        }
        document.getElementById("upn")
            .addEventListener("change", function () {
                document.getElementById("validateUpn").style.display = "none";
            }, false);
        document.getElementById("upn")
            .addEventListener("keyup", function () {
                document.getElementById("validateUpn").style.display = "none";
            }, false);
        document.getElementById("loader1").hidden = true;
        document.getElementById("process").addEventListener("click", function () {
            document.getElementById("loader1").hidden = false;
        }, false);
    })();
</script>
<script type="text/javascript">
    var ContextualMenuElements = document.querySelectorAll(".ms-ContextualMenuExample");
    for (var i = 0; i < ContextualMenuElements.length; i++) {
        var ButtonElement = ContextualMenuElements[i].querySelector(".ms-Button");
        var ContextualMenuElement = ContextualMenuElements[i].querySelector(".ms-ContextualMenu");
        new fabric['ContextualMenu'](ContextualMenuElement, ButtonElement);
    }
</script>

wvd-templates/diagnostics-sample/src/MSFT.WVD.Diagnostics/Views/DiagnoseIssues/returnToIndex.cshtml
@model DiagonizePageViewModel
@using MSFT.WVD.Diagnostics.Common.Models
@{
    ViewData["Title"] = "Diagnose Issues";

}

<div class="width-100 content-section">
    <h2>Search activity feed</h2>
    <br />
    <form asp-controller="DiagnoseIssues" asp-action="IssuesInterval" method="post" id="myform" role="form">
        <div class="ms-Grid" dir="ltr">
            <div class="ms-Grid-row">
                <div class="form-wrap ms-Grid-col ms-xxxl3 ms-xxl3 ms-xl12 m-b-20">
                    <label asp-for="DiagonizeQuery.UPN" class="control-label ms-xxxl2 ms-xxl2 ms-xl2"><b>User UPN</b><span class="red">*</span></label>
                    <div class="input-wrap ms-xxxl10 ms-xxl12 ms-xl12">
                        <input asp-for="@Model.DiagonizeQuery.UPN" class="form-control" id="upn" placeholder="Enter User UPN" />
                        <span asp-validation-for="DiagonizeQuery.UPN" id="validateUpn" class="error-msg validate"></span>
                    </div>
                </div>
                <div class="form-wrap ms-Grid-col ms-xxxl3 ms-xxl3 ms-xl12 m-b-20">
                    <label asp-for="DiagonizeQuery.ActivityType" class="control-label ms-xxxl2 ms-xxl2 ms-xl2"><b>Activity type</b><span class="red">*</span></label>
                    <div class="input-wrap ms-xxxl10 ms-xxl12 ms-xl12">
                        <select size="1" asp-for="DiagonizeQuery.ActivityType" asp-items="Html.GetEnumSelectList<ActivityType>().Where(x=> x.Text != ActivityType.None.ToString() ).ToList()" class="form-control  width-100 " id="activityType"></select>
                    </div>
                </div>
                <div class="form-wrap ms-Grid-col ms-xxxl3 ms-xxl4 ms-xl12 p-l-r-15 m-b-20">
                    <button type="submit" class="ms-Button primary-btn" id="process">
                        <span class="ms-Button-label">Search</span>
                    </button>
                </div>
            </div>
        </div>
    </form>
    <hr />
    @*@if (Model.ConnectionActivity == null || Model.ManagementActivity == null || Model.FeedActivity == null || Model.ConnectionActivity.Count == 0 || Model.ManagementActivity.Count == 0 || Model.FeedActivity.Count == 0)
        {
            <div id="loader1" class="loader"></div>
        }*@
    <div class="ContextualMenuWrap">
        <div class="ms-ContextualMenuExample filter-btn float-right">
            <button class="ms-Button ms-Button--default">
                <span class="ms-Button-label"><i class="ms-Icon ms-Icon--Filter" aria-hidden="true"></i>Filter</span>
            </button>
            <ul class="ms-ContextualMenu is-hidden ms-ContextualMenu--multiselect">
                <li class="ms-ContextualMenu-item ms-ContextualMenu-item--header">
                    <i class="ms-Icon ms-Icon--Filter" aria-hidden="true"></i>
                    <a style="text-decoration:none; color:#0078d7; padding-left:8px;" asp-controller="DiagnoseIssues" asp-action="ClearFilter"><b>Clear all Filters</b></a>
                </li>
                <li class="ms-ContextualMenu-item ms-ContextualMenu-item--divider"></li>
                <li class="ms-ContextualMenu-item ms-ContextualMenu-item--header"><b>Issues from</b></li>
                <li class="ms-ContextualMenu-item">
                    @{
                        IDictionary<string, string> routeData = new Dictionary<string, string>();
                        routeData.Add("interval", "Lastonehour");
                        routeData.Add("upn", Model.DiagonizeQuery.UPN);
                    }
                    <a class="ms-ContextualMenu-link" tabindex="1" asp-controller="DiagnoseIssues" asp-action="IssuesInterval" asp-all-route-data="routeData">Last hour</a>
                </li>
                <li class="ms-ContextualMenu-item">
                    @{
                        IDictionary<string, string> routeData1 = new Dictionary<string, string>();
                        routeData1.Add("interval", "sixhoursago");
                        routeData1.Add("upn", Model.DiagonizeQuery.UPN);
                    }
                    <a class="ms-ContextualMenu-link" tabindex="1" asp-controller="DiagnoseIssues" asp-action="IssuesInterval" asp-all-route-data="routeData1">6 hours ago</a>
                </li>
                <li class="ms-ContextualMenu-item">
                    @{
                        IDictionary<string, string> routeData2 = new Dictionary<string, string>();
                        routeData2.Add("interval", "onedayago");
                        routeData2.Add("upn", Model.DiagonizeQuery.UPN);
                    }
                    <a class="ms-ContextualMenu-link" tabindex="1" asp-controller="DiagnoseIssues" asp-action="IssuesInterval" asp-all-route-data="routeData2">1 day ago</a>
                </li>
                <li class="ms-ContextualMenu-item">
                    @{
                        IDictionary<string, string> routeData3 = new Dictionary<string, string>();
                        routeData3.Add("interval", "onweekago");
                        routeData3.Add("upn", Model.DiagonizeQuery.UPN);
                    }
                    <a class="ms-ContextualMenu-link" tabindex="1" asp-controller="DiagnoseIssues" asp-action="IssuesInterval" asp-all-route-data="routeData3">1 week ago</a>
                </li>
                <li class="ms-ContextualMenu-item ms-ContextualMenu-item--divider"></li>
                <li class="ms-ContextualMenu-item ms-ContextualMenu-item--header"><b>Outcome</b></li>
                <li class="ms-ContextualMenu-item">
                    @{
                        IDictionary<string, string> routeData4 = new Dictionary<string, string>();
                        routeData4.Add("outcome", "Failure");
                        routeData4.Add("upn", Model.DiagonizeQuery.UPN);
                    }
                    <a class="ms-ContextualMenu-link" tabindex="1" asp-controller="DiagnoseIssues" asp-action="IssuesInterval" asp-all-route-data="routeData4">Failed</a>
                </li>
                <li class="ms-ContextualMenu-item">
                    @{
                        IDictionary<string, string> routeData5 = new Dictionary<string, string>();
                        routeData5.Add("outcome", "Success");
                        routeData5.Add("upn", Model.DiagonizeQuery.UPN);
                    }
                    <a class="ms-ContextualMenu-link" tabindex="1" asp-controller="DiagnoseIssues" asp-action="IssuesInterval" asp-all-route-data="routeData5">Success</a>
                </li>
                <li class="ms-ContextualMenu-item">
                    @{
                        IDictionary<string, string> routeData6 = new Dictionary<string, string>();
                        routeData6.Add("outcome", "All");
                        routeData6.Add("upn", Model.DiagonizeQuery.UPN);
                    }
                    <a class="ms-ContextualMenu-link" tabindex="1" asp-controller="DiagnoseIssues" asp-action="IssuesInterval" asp-all-route-data="routeData6">All</a>
                </li>
            </ul>
        </div>
        <div class="clear"></div>
    </div>
    <table class="ms-Table">
        <thead>
            <tr>
                <th asp-for="Start time">Start time</th>
                <th asp-for="End time">End time</th>
                <th asp-for="Outcome">Outcome</th>
                <th asp-for="Service error">Service error</th>
                <th asp-for="Error">Error</th>
                <th asp-for="Session Host">Session host</th>
                <th asp-for="Client">Client</th>
                <th asp-for="Client IP">Client IP</th>
                <th asp-for="Host pool">Host pool</th>
                <th asp-for="Tenant">Tenant</th>
                <th asp-for="Activity ID">Activity ID</th>
            </tr>
        </thead>
    </table>
    <div id="Indexnodata">
        <h5 style="text-align:center">No data yet.</h5><p style="text-align:center">Please search User UPN to see data</p>
    </div>

</div>
<script>
    (function () {
        document.getElementById("Diagnosebreadcrumb").style.display = "block";
        var ContextualMenuElements = document.querySelectorAll(".ms-ContextualMenuExample");
        for (var i = 0; i < ContextualMenuElements.length; i++) {
            var ButtonElement = ContextualMenuElements[i].querySelector(".ms-Button");
            var ContextualMenuElement = ContextualMenuElements[i].querySelector(".ms-ContextualMenu");
            new fabric['ContextualMenu'](ContextualMenuElement, ButtonElement);
        }
        var TableElements = document.querySelectorAll(".ms-Table");
        for (var i = 0; i < TableElements.length; i++) {
            new fabric['Table'](TableElements[i]);
        }
        document.getElementById("upn")
            .addEventListener("change", function () {
                document.getElementById("validateUpn").style.display = "none";
            }, false);
        document.getElementById("upn")
            .addEventListener("keyup", function () {
                document.getElementById("validateUpn").style.display = "none";
            }, false);
        document.getElementById("loader1").hidden = true;
        document.getElementById("process").addEventListener("click", function () {
            document.getElementById("loader1").hidden = false;
        }, false);
    })();
</script>